name: CI

on:
  schedule:
    - cron: '0 * * * *' # Rulează o dată pe oră
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rularea scriptului de analiză
        run: |
          python scripts/ai_trading_bot.py

